require("bauti.plugins-setup") -- make sure this is first!
require("bauti.core.options")
require("bauti.core.keymappings")
require("bauti.core.colorscheme")
require("bauti.plugin.comments")
require("bauti.plugin.nvim-tree")
require("bauti.plugin.lualine")
require("bauti.plugin.telescope")
require("bauti.plugin.nvim-cmp")
require("bauti.plugin.lsp.mason")
require("bauti.plugin.lsp.lspsaga")
require("bauti.plugin.lsp.lspconfig")
require("bauti.plugin.lsp.null-ls")
require("bauti.plugin.autopairs")
require("bauti.plugin.treesitter")
require("bauti.plugin.gitsigns")
